# Things run before a commit. If files are changed from these, you need to add and commit.
# https://pre-commit.com/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-symlinks
      - id: check-toml
      - id: destroyed-symlinks

  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black

  # TypeScript/JavaScript formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, markdown, yaml]

  # TypeScript/JavaScript linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0 # Use ESLint 8.x which supports .eslintrc.json
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - typescript@5.7.2
          - '@typescript-eslint/parser@7.18.0'
          - '@typescript-eslint/eslint-plugin@7.18.0'
          - eslint-config-prettier@9.1.0
          - eslint-plugin-react@7.37.2
          - eslint-plugin-react-hooks@4.6.2
